
package org.huahsin.jaxws.staff;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISeniorManager", targetNamespace = "http://staff.huahsin.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISeniorManager {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getID", targetNamespace = "http://staff.huahsin.org/", className = "org.huahsin.jaxws.staff.GetID")
    @ResponseWrapper(localName = "getIDResponse", targetNamespace = "http://staff.huahsin.org/", className = "org.huahsin.jaxws.staff.GetIDResponse")
    @Action(input = "http://staff.huahsin.org/ISeniorManager/getIDRequest", output = "http://staff.huahsin.org/ISeniorManager/getIDResponse")
    public String getID();

}
