
package org.huahsin.jaxws.staff;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SeniorManagerService", targetNamespace = "http://staff.huahsin.org/", wsdlLocation = "file:/C:/workspace/ws1/resources/wsdl/SeniorManager.wsdl")
public class SeniorManagerService
    extends Service
{

    private final static URL SENIORMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SENIORMANAGERSERVICE_EXCEPTION;
    private final static QName SENIORMANAGERSERVICE_QNAME = new QName("http://staff.huahsin.org/", "SeniorManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/workspace/ws1/resources/wsdl/SeniorManager.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENIORMANAGERSERVICE_WSDL_LOCATION = url;
        SENIORMANAGERSERVICE_EXCEPTION = e;
    }

    public SeniorManagerService() {
        super(__getWsdlLocation(), SENIORMANAGERSERVICE_QNAME);
    }

    public SeniorManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENIORMANAGERSERVICE_QNAME, features);
    }

    public SeniorManagerService(URL wsdlLocation) {
        super(wsdlLocation, SENIORMANAGERSERVICE_QNAME);
    }

    public SeniorManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENIORMANAGERSERVICE_QNAME, features);
    }

    public SeniorManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeniorManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISeniorManager
     */
    @WebEndpoint(name = "SeniorManagerPort")
    public ISeniorManager getSeniorManagerPort() {
        return super.getPort(new QName("http://staff.huahsin.org/", "SeniorManagerPort"), ISeniorManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISeniorManager
     */
    @WebEndpoint(name = "SeniorManagerPort")
    public ISeniorManager getSeniorManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://staff.huahsin.org/", "SeniorManagerPort"), ISeniorManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENIORMANAGERSERVICE_EXCEPTION!= null) {
            throw SENIORMANAGERSERVICE_EXCEPTION;
        }
        return SENIORMANAGERSERVICE_WSDL_LOCATION;
    }

}
