
package org.huahsin.async;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHelloWorld", targetNamespace = "http://webmethod.huahsin.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHelloWorld {


    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<org.huahsin.async.SayHelloWorldResponse>
     */
    @WebMethod(operationName = "sayHelloWorld")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://webmethod.huahsin.org/", className = "org.huahsin.async.SayHelloWorld")
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://webmethod.huahsin.org/", className = "org.huahsin.async.SayHelloWorldResponse")
    public Response<SayHelloWorldResponse> sayHelloWorldAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "sayHelloWorld")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://webmethod.huahsin.org/", className = "org.huahsin.async.SayHelloWorld")
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://webmethod.huahsin.org/", className = "org.huahsin.async.SayHelloWorldResponse")
    public Future<?> sayHelloWorldAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SayHelloWorldResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://webmethod.huahsin.org/", className = "org.huahsin.async.SayHelloWorld")
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://webmethod.huahsin.org/", className = "org.huahsin.async.SayHelloWorldResponse")
    @Action(input = "http://webmethod.huahsin.org/IHelloWorld/sayHelloWorldRequest", output = "http://webmethod.huahsin.org/IHelloWorld/sayHelloWorldResponse")
    public String sayHelloWorld();

}
